version: '3.1'
services:
  docker-registry:
    container_name: docker-registry
    image: registry:2
    ports:
      - 5000:5000
    restart: always
    volumes:
      - ./docker-registry-volume:/var/lib/registry
    networks:
      - poc-network

networks:
  poc-network:
    driver: bridge
    external: true
