CREATE ROLE robot;
ALTER ROLE robot WITH SUPERUSER
INHERIT
CREATEROLE
CREATEDB
LOGIN
NOREPLICATION
NOBYPASSRLS
PASSWORD 'robotpass';

CREATE DATABASE user_db WITH TEMPLATE = template0 OWNER = postgres;
GRANT ALL ON DATABASE user_db TO robot;

CREATE DATABASE address_db WITH TEMPLATE = template0 OWNER = postgres;
GRANT ALL ON DATABASE address_db TO robot;

CREATE DATABASE phone_db WITH TEMPLATE = template0 OWNER = postgres;
GRANT ALL ON DATABASE phone_db TO robot;

